// Generated by gencpp from file forest_fire_detection_system/SegmentSmoke.msg
// DO NOT EDIT!


#ifndef FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_SEGMENTSMOKE_H
#define FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_SEGMENTSMOKE_H

#include <ros/service_traits.h>


#include <forest_fire_detection_system/SegmentSmokeRequest.h>
#include <forest_fire_detection_system/SegmentSmokeResponse.h>


namespace forest_fire_detection_system
{

struct SegmentSmoke
{

typedef SegmentSmokeRequest Request;
typedef SegmentSmokeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SegmentSmoke
} // namespace forest_fire_detection_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::forest_fire_detection_system::SegmentSmoke > {
  static const char* value()
  {
    return "11478f9622703c748b49ba15c30aea4e";
  }

  static const char* value(const ::forest_fire_detection_system::SegmentSmoke&) { return value(); }
};

template<>
struct DataType< ::forest_fire_detection_system::SegmentSmoke > {
  static const char* value()
  {
    return "forest_fire_detection_system/SegmentSmoke";
  }

  static const char* value(const ::forest_fire_detection_system::SegmentSmoke&) { return value(); }
};


// service_traits::MD5Sum< ::forest_fire_detection_system::SegmentSmokeRequest> should match
// service_traits::MD5Sum< ::forest_fire_detection_system::SegmentSmoke >
template<>
struct MD5Sum< ::forest_fire_detection_system::SegmentSmokeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::forest_fire_detection_system::SegmentSmoke >::value();
  }
  static const char* value(const ::forest_fire_detection_system::SegmentSmokeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::forest_fire_detection_system::SegmentSmokeRequest> should match
// service_traits::DataType< ::forest_fire_detection_system::SegmentSmoke >
template<>
struct DataType< ::forest_fire_detection_system::SegmentSmokeRequest>
{
  static const char* value()
  {
    return DataType< ::forest_fire_detection_system::SegmentSmoke >::value();
  }
  static const char* value(const ::forest_fire_detection_system::SegmentSmokeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::forest_fire_detection_system::SegmentSmokeResponse> should match
// service_traits::MD5Sum< ::forest_fire_detection_system::SegmentSmoke >
template<>
struct MD5Sum< ::forest_fire_detection_system::SegmentSmokeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::forest_fire_detection_system::SegmentSmoke >::value();
  }
  static const char* value(const ::forest_fire_detection_system::SegmentSmokeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::forest_fire_detection_system::SegmentSmokeResponse> should match
// service_traits::DataType< ::forest_fire_detection_system::SegmentSmoke >
template<>
struct DataType< ::forest_fire_detection_system::SegmentSmokeResponse>
{
  static const char* value()
  {
    return DataType< ::forest_fire_detection_system::SegmentSmoke >::value();
  }
  static const char* value(const ::forest_fire_detection_system::SegmentSmokeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_SEGMENTSMOKE_H
