// Generated by gencpp from file forest_fire_detection_system/ToggleGrabDataDepthEstimation.msg
// DO NOT EDIT!


#ifndef FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATION_H
#define FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATION_H

#include <ros/service_traits.h>


#include <forest_fire_detection_system/ToggleGrabDataDepthEstimationRequest.h>
#include <forest_fire_detection_system/ToggleGrabDataDepthEstimationResponse.h>


namespace forest_fire_detection_system
{

struct ToggleGrabDataDepthEstimation
{

typedef ToggleGrabDataDepthEstimationRequest Request;
typedef ToggleGrabDataDepthEstimationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleGrabDataDepthEstimation
} // namespace forest_fire_detection_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation > {
  static const char* value()
  {
    return "0304abb62c1d15138b7d0bfcf0865362";
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimation&) { return value(); }
};

template<>
struct DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation > {
  static const char* value()
  {
    return "forest_fire_detection_system/ToggleGrabDataDepthEstimation";
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimation&) { return value(); }
};


// service_traits::MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest> should match
// service_traits::MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >
template<>
struct MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >::value();
  }
  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest> should match
// service_traits::DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >
template<>
struct DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest>
{
  static const char* value()
  {
    return DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >::value();
  }
  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse> should match
// service_traits::MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >
template<>
struct MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >::value();
  }
  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse> should match
// service_traits::DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >
template<>
struct DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse>
{
  static const char* value()
  {
    return DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimation >::value();
  }
  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATION_H
