// Generated by gencpp from file forest_fire_detection_system/ToggleGrabDataDepthEstimationResponse.msg
// DO NOT EDIT!


#ifndef FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATIONRESPONSE_H
#define FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace forest_fire_detection_system
{
template <class ContainerAllocator>
struct ToggleGrabDataDepthEstimationResponse_
{
  typedef ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> Type;

  ToggleGrabDataDepthEstimationResponse_()
    : result(false)  {
    }
  ToggleGrabDataDepthEstimationResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleGrabDataDepthEstimationResponse_

typedef ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<std::allocator<void> > ToggleGrabDataDepthEstimationResponse;

typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse > ToggleGrabDataDepthEstimationResponsePtr;
typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse const> ToggleGrabDataDepthEstimationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator1> & lhs, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator1> & lhs, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace forest_fire_detection_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "forest_fire_detection_system/ToggleGrabDataDepthEstimationResponse";
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleGrabDataDepthEstimationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATIONRESPONSE_H
