// Generated by gencpp from file forest_fire_detection_system/ToggleGrabDataDepthEstimationRequest.msg
// DO NOT EDIT!


#ifndef FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATIONREQUEST_H
#define FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace forest_fire_detection_system
{
template <class ContainerAllocator>
struct ToggleGrabDataDepthEstimationRequest_
{
  typedef ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> Type;

  ToggleGrabDataDepthEstimationRequest_()
    : start(false)  {
    }
  ToggleGrabDataDepthEstimationRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleGrabDataDepthEstimationRequest_

typedef ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<std::allocator<void> > ToggleGrabDataDepthEstimationRequest;

typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest > ToggleGrabDataDepthEstimationRequestPtr;
typedef boost::shared_ptr< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest const> ToggleGrabDataDepthEstimationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator1> & lhs, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator1> & lhs, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace forest_fire_detection_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "forest_fire_detection_system/ToggleGrabDataDepthEstimationRequest";
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# toggle the GrabData\n"
"bool start\n"
"\n"
;
  }

  static const char* value(const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleGrabDataDepthEstimationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::forest_fire_detection_system::ToggleGrabDataDepthEstimationRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOREST_FIRE_DETECTION_SYSTEM_MESSAGE_TOGGLEGRABDATADEPTHESTIMATIONREQUEST_H
