(cl:in-package forest_fire_detection_system-msg)
(cl:export '(HEADER-VAL
          HEADER
          IR_IMG_WIDTH-VAL
          IR_IMG_WIDTH
          IR_IMG_HEIGHT-VAL
          IR_IMG_HEIGHT
          RGB_IMG_WIDTH-VAL
          RGB_IMG_WIDTH
          RGB_IMG_HEIGHT-VAL
          RGB_IMG_HEIGHT
          TARGET_TYPE-VAL
          TARGET_TYPE
          FOCUSE_MODE-VAL
          FOCUSE_MODE
          IR_IMG_X-VAL
          IR_IMG_X
          IR_IMG_Y-VAL
          IR_IMG_Y
          RGB_IMG_X-VAL
          RGB_IMG_X
          RGB_IMG_Y-VAL
          RGB_IMG_Y
          SCALE-VAL
          SCALE
          OFFSET_X-VAL
          OFFSET_X
          OFFSET_Y-VAL
          OFFSET_Y
))