# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from forest_fire_detection_system/SingleFireIR.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SingleFireIR(genpy.Message):
  _md5sum = "9ea94f8510b24f699c5a36dcda64a4f8"
  _type = "forest_fire_detection_system/SingleFireIR"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# image shape
uint16 img_width
uint16 img_height

# reszie shape
uint16 resize_img_width
uint16 resize_img_height

# target type
uint8 IS_BACKGROUND = 0
uint8 IS_HEAT = 1
uint8 IS_UNKNOWN = 255

uint8 target_type

# the x and y pos (sub-pixel) of the single fire, opencv style coordinates
float32 img_x
float32 img_y


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  IS_BACKGROUND = 0
  IS_HEAT = 1
  IS_UNKNOWN = 255

  __slots__ = ['header','img_width','img_height','resize_img_width','resize_img_height','target_type','img_x','img_y']
  _slot_types = ['std_msgs/Header','uint16','uint16','uint16','uint16','uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,img_width,img_height,resize_img_width,resize_img_height,target_type,img_x,img_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SingleFireIR, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.img_width is None:
        self.img_width = 0
      if self.img_height is None:
        self.img_height = 0
      if self.resize_img_width is None:
        self.resize_img_width = 0
      if self.resize_img_height is None:
        self.resize_img_height = 0
      if self.target_type is None:
        self.target_type = 0
      if self.img_x is None:
        self.img_x = 0.
      if self.img_y is None:
        self.img_y = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.img_width = 0
      self.img_height = 0
      self.resize_img_width = 0
      self.resize_img_height = 0
      self.target_type = 0
      self.img_x = 0.
      self.img_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4HB2f().pack(_x.img_width, _x.img_height, _x.resize_img_width, _x.resize_img_height, _x.target_type, _x.img_x, _x.img_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.img_width, _x.img_height, _x.resize_img_width, _x.resize_img_height, _x.target_type, _x.img_x, _x.img_y,) = _get_struct_4HB2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4HB2f().pack(_x.img_width, _x.img_height, _x.resize_img_width, _x.resize_img_height, _x.target_type, _x.img_x, _x.img_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.img_width, _x.img_height, _x.resize_img_width, _x.resize_img_height, _x.target_type, _x.img_x, _x.img_y,) = _get_struct_4HB2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4HB2f = None
def _get_struct_4HB2f():
    global _struct_4HB2f
    if _struct_4HB2f is None:
        _struct_4HB2f = struct.Struct("<4HB2f")
    return _struct_4HB2f
