# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from forest_fire_detection_system/SingleFireFuse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SingleFireFuse(genpy.Message):
  _md5sum = "5acee9e57a872fd936b9b0d95ff37894"
  _type = "forest_fire_detection_system/SingleFireFuse"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# image detecting on info
uint16 ir_img_width
uint16 ir_img_height
uint16 rgb_img_width
uint16 rgb_img_height

# target type
uint8 IS_BACKGROUND = 0
uint8 IS_TARGET = 1
uint8 IS_UNKNOWN = 255

uint8 target_type

# focuse mode
uint8 USE_NONE = 0
uint8 USE_IR  = 1
uint8 USE_RGB  = 2

uint8 focuse_mode

# the x and y pos (sub-pixel) of the single fire, opencv style coordinates
float32 ir_img_x
float32 ir_img_y
float32 rgb_img_x
float32 rgb_img_y

# translation(ir->rgb)
float32 scale
float32 offset_x
float32 offset_y

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  IS_BACKGROUND = 0
  IS_TARGET = 1
  IS_UNKNOWN = 255
  USE_NONE = 0
  USE_IR = 1
  USE_RGB = 2

  __slots__ = ['header','ir_img_width','ir_img_height','rgb_img_width','rgb_img_height','target_type','focuse_mode','ir_img_x','ir_img_y','rgb_img_x','rgb_img_y','scale','offset_x','offset_y']
  _slot_types = ['std_msgs/Header','uint16','uint16','uint16','uint16','uint8','uint8','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ir_img_width,ir_img_height,rgb_img_width,rgb_img_height,target_type,focuse_mode,ir_img_x,ir_img_y,rgb_img_x,rgb_img_y,scale,offset_x,offset_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SingleFireFuse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ir_img_width is None:
        self.ir_img_width = 0
      if self.ir_img_height is None:
        self.ir_img_height = 0
      if self.rgb_img_width is None:
        self.rgb_img_width = 0
      if self.rgb_img_height is None:
        self.rgb_img_height = 0
      if self.target_type is None:
        self.target_type = 0
      if self.focuse_mode is None:
        self.focuse_mode = 0
      if self.ir_img_x is None:
        self.ir_img_x = 0.
      if self.ir_img_y is None:
        self.ir_img_y = 0.
      if self.rgb_img_x is None:
        self.rgb_img_x = 0.
      if self.rgb_img_y is None:
        self.rgb_img_y = 0.
      if self.scale is None:
        self.scale = 0.
      if self.offset_x is None:
        self.offset_x = 0.
      if self.offset_y is None:
        self.offset_y = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.ir_img_width = 0
      self.ir_img_height = 0
      self.rgb_img_width = 0
      self.rgb_img_height = 0
      self.target_type = 0
      self.focuse_mode = 0
      self.ir_img_x = 0.
      self.ir_img_y = 0.
      self.rgb_img_x = 0.
      self.rgb_img_y = 0.
      self.scale = 0.
      self.offset_x = 0.
      self.offset_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4H2B7f().pack(_x.ir_img_width, _x.ir_img_height, _x.rgb_img_width, _x.rgb_img_height, _x.target_type, _x.focuse_mode, _x.ir_img_x, _x.ir_img_y, _x.rgb_img_x, _x.rgb_img_y, _x.scale, _x.offset_x, _x.offset_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 38
      (_x.ir_img_width, _x.ir_img_height, _x.rgb_img_width, _x.rgb_img_height, _x.target_type, _x.focuse_mode, _x.ir_img_x, _x.ir_img_y, _x.rgb_img_x, _x.rgb_img_y, _x.scale, _x.offset_x, _x.offset_y,) = _get_struct_4H2B7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4H2B7f().pack(_x.ir_img_width, _x.ir_img_height, _x.rgb_img_width, _x.rgb_img_height, _x.target_type, _x.focuse_mode, _x.ir_img_x, _x.ir_img_y, _x.rgb_img_x, _x.rgb_img_y, _x.scale, _x.offset_x, _x.offset_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 38
      (_x.ir_img_width, _x.ir_img_height, _x.rgb_img_width, _x.rgb_img_height, _x.target_type, _x.focuse_mode, _x.ir_img_x, _x.ir_img_y, _x.rgb_img_x, _x.rgb_img_y, _x.scale, _x.offset_x, _x.offset_y,) = _get_struct_4H2B7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4H2B7f = None
def _get_struct_4H2B7f():
    global _struct_4H2B7f
    if _struct_4H2B7f is None:
        _struct_4H2B7f = struct.Struct("<4H2B7f")
    return _struct_4H2B7f
