general_params:
  camera_pitch: -30
  release_delay: -1900
  height: 7
  lateral_adjustment: 0  # minus is toward left
  # gimbal_yaw_adjustment: -80
  gimbal_yaw_adjustment: -15
  threshold: 2
  run_up_distance: 14
  apply_fuzzy_control: true
  velocity_max: 0.1 # fuzzy controller maximum velocity
  user_input_lateral_adjustment: false 

