general_params:
  camera_pitch: -30
  release_delay: -1900
  height: 7
  lateral_adjustment: 0  # minus is toward left
  # gimbal_yaw_adjustment: -80
  gimbal_yaw_adjustment: -12
  threshold: 2
  run_up_distance: 14
  velocity: 0.5
  apply_fuzzy_control: False

