general_params:
  camera_pitch: -30
  release_delay: -3000
  height: 7
  lateral_adjustment: 0  # minus is toward left
  # gimbal_yaw_adjustment: -80
  gimbal_yaw_adjustment: -3
  threshold: 1.8
  run_up_distance: 10.5
  apply_fuzzy_control: true
  velocity_max: 0.1 # fuzzy controller maximum velocity
  user_input_lateral_adjustment: true
  fake_fire_spot_counter_mode: true
  yaw_rate_adjustmnet_for_circular_path: 0
  approach_absolute_velocity: 1
  time_of_approach: 13000
  extra_yaw_adjustment: true

