(cl:defpackage forest_fire_detection_system-srv
  (:use )
  (:export
   "SEGMENTSMOKE"
   "<SEGMENTSMOKE-REQUEST>"
   "SEGMENTSMOKE-REQUEST"
   "<SEGMENTSMOKE-RESPONSE>"
   "SEGMENTSMOKE-RESPONSE"
   "TOGGLEGRABDATADEPTHESTIMATION"
   "<TOGGLEGRABDATADEPTHESTIMATION-REQUEST>"
   "TOGGLEGRABDATADEPTHESTIMATION-REQUEST"
   "<TOGGLEGRABDATADEPTHESTIMATION-RESPONSE>"
   "TOGGLEGRABDATADEPTHESTIMATION-RESPONSE"
  ))

